// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBqRpgx3n2oNUuW-MOV7y5eiwn9IdUlZQ',
    appId: '1:389473436868:web:fc3cf17368798017aeb591',
    messagingSenderId: '389473436868',
    projectId: 'session16-fae79',
    authDomain: 'session16-fae79.firebaseapp.com',
    storageBucket: 'session16-fae79.appspot.com',
    measurementId: 'G-9D6XRCS9E4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtgjX-e-ae-64mumjDoPylLiFmDaGggl4',
    appId: '1:389473436868:android:9c7211ddc919a5f8aeb591',
    messagingSenderId: '389473436868',
    projectId: 'session16-fae79',
    storageBucket: 'session16-fae79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUtUQagbU1Z12Bmyc_fgU-96nRk37zMJg',
    appId: '1:389473436868:ios:de824260cc4fca8caeb591',
    messagingSenderId: '389473436868',
    projectId: 'session16-fae79',
    storageBucket: 'session16-fae79.appspot.com',
    iosBundleId: 'com.example.session16',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUtUQagbU1Z12Bmyc_fgU-96nRk37zMJg',
    appId: '1:389473436868:ios:de824260cc4fca8caeb591',
    messagingSenderId: '389473436868',
    projectId: 'session16-fae79',
    storageBucket: 'session16-fae79.appspot.com',
    iosBundleId: 'com.example.session16',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBqRpgx3n2oNUuW-MOV7y5eiwn9IdUlZQ',
    appId: '1:389473436868:web:249967299dc7d56aaeb591',
    messagingSenderId: '389473436868',
    projectId: 'session16-fae79',
    authDomain: 'session16-fae79.firebaseapp.com',
    storageBucket: 'session16-fae79.appspot.com',
    measurementId: 'G-TH5TZ8LPQ9',
  );
}
