// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdYjxYpSjeClsD8EkkUBOTVJ_9Md5otRU',
    appId: '1:866003115552:web:e381e42c6742320d5ba645',
    messagingSenderId: '866003115552',
    projectId: 'market-we',
    authDomain: 'market-we.firebaseapp.com',
    storageBucket: 'market-we.appspot.com',
    measurementId: 'G-VBPN8ZTC7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYztGdbXajsA2o3_WooHP_4_fJqLaZeII',
    appId: '1:866003115552:android:050966a0f567b1485ba645',
    messagingSenderId: '866003115552',
    projectId: 'market-we',
    storageBucket: 'market-we.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhuDo1vAyZRzqcf9EU2Q0OuRFDTgL1rDQ',
    appId: '1:866003115552:ios:878597cd550b11615ba645',
    messagingSenderId: '866003115552',
    projectId: 'market-we',
    storageBucket: 'market-we.appspot.com',
    iosBundleId: 'com.example.marketWe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhuDo1vAyZRzqcf9EU2Q0OuRFDTgL1rDQ',
    appId: '1:866003115552:ios:878597cd550b11615ba645',
    messagingSenderId: '866003115552',
    projectId: 'market-we',
    storageBucket: 'market-we.appspot.com',
    iosBundleId: 'com.example.marketWe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdYjxYpSjeClsD8EkkUBOTVJ_9Md5otRU',
    appId: '1:866003115552:web:af87b9cebefa47355ba645',
    messagingSenderId: '866003115552',
    projectId: 'market-we',
    authDomain: 'market-we.firebaseapp.com',
    storageBucket: 'market-we.appspot.com',
    measurementId: 'G-ZHQTG1D56R',
  );
}
