// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC64rlxZg1h6NBiiaBBslXfS7YEMVQQJUI',
    appId: '1:895031200590:web:5f7970451d88401c3f2c1f',
    messagingSenderId: '895031200590',
    projectId: 'firbase-8e0b4',
    authDomain: 'firbase-8e0b4.firebaseapp.com',
    storageBucket: 'firbase-8e0b4.appspot.com',
    measurementId: 'G-9VQL17L03M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ6vak3qT-O1co4_qOhXZiLWH4mGR-peg',
    appId: '1:895031200590:android:2f9d57ab10b60c203f2c1f',
    messagingSenderId: '895031200590',
    projectId: 'firbase-8e0b4',
    storageBucket: 'firbase-8e0b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWzAHNWxTZvYGoNhpqEnrqx-_i-NrB7AE',
    appId: '1:895031200590:ios:5cc90e3c8c72e5923f2c1f',
    messagingSenderId: '895031200590',
    projectId: 'firbase-8e0b4',
    storageBucket: 'firbase-8e0b4.appspot.com',
    iosBundleId: 'com.example.firbase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWzAHNWxTZvYGoNhpqEnrqx-_i-NrB7AE',
    appId: '1:895031200590:ios:5cc90e3c8c72e5923f2c1f',
    messagingSenderId: '895031200590',
    projectId: 'firbase-8e0b4',
    storageBucket: 'firbase-8e0b4.appspot.com',
    iosBundleId: 'com.example.firbase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC64rlxZg1h6NBiiaBBslXfS7YEMVQQJUI',
    appId: '1:895031200590:web:cc79dbf7b9c4a4613f2c1f',
    messagingSenderId: '895031200590',
    projectId: 'firbase-8e0b4',
    authDomain: 'firbase-8e0b4.firebaseapp.com',
    storageBucket: 'firbase-8e0b4.appspot.com',
    measurementId: 'G-G9P8TFPYFV',
  );
}
