// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZyJv69RmovS_SLabBdt477cxu3E14bOQ',
    appId: '1:320880192368:web:628ee4c811bfcb1d5efdb5',
    messagingSenderId: '320880192368',
    projectId: 'fir-3840b',
    authDomain: 'fir-3840b.firebaseapp.com',
    storageBucket: 'fir-3840b.appspot.com',
    measurementId: 'G-V780H6FKMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfwUtmBwVxaJZbJLOsc3X2w3JWc50oDyg',
    appId: '1:320880192368:android:bdcbb510c19f7c485efdb5',
    messagingSenderId: '320880192368',
    projectId: 'fir-3840b',
    storageBucket: 'fir-3840b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoQh-5jNuF1mbx5NmOUusM8QrMBYHj_zA',
    appId: '1:320880192368:ios:e71dbde9a36a10c95efdb5',
    messagingSenderId: '320880192368',
    projectId: 'fir-3840b',
    storageBucket: 'fir-3840b.appspot.com',
    iosBundleId: 'com.example.firbase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoQh-5jNuF1mbx5NmOUusM8QrMBYHj_zA',
    appId: '1:320880192368:ios:e71dbde9a36a10c95efdb5',
    messagingSenderId: '320880192368',
    projectId: 'fir-3840b',
    storageBucket: 'fir-3840b.appspot.com',
    iosBundleId: 'com.example.firbase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZyJv69RmovS_SLabBdt477cxu3E14bOQ',
    appId: '1:320880192368:web:35137954ee21e7fb5efdb5',
    messagingSenderId: '320880192368',
    projectId: 'fir-3840b',
    authDomain: 'fir-3840b.firebaseapp.com',
    storageBucket: 'fir-3840b.appspot.com',
    measurementId: 'G-4DXR8ZHCVC',
  );

}